<a href="https://colab.research.google.com/github/jessiejxyu2/ist526/blob/main/High_D_Scagnostic_and_Scatterplot_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Essential Libraries

In [ ]:
# python visualization libraries
import matplotlib.pyplot as plt
import matplotlib as mpl
# from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import plotly.express as px
%matplotlib inline

import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots as subplots

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Steps to High Dimensional Data Reduction

## Loading data

### Option 1. Loading large dataset from Google Drive
For large-scale datasets, it is not possible to load them from GitHub due to network traffics and latency. So, we need to load them from  Google Drive. Steps are shown below.

**Make sure you to comment the following blocks if you are loading data from GitHub.

### Mounting Google Drive

In [ ]:
import os

# mount drive
from google.colab import drive
drive.mount('/content/drive')


# edit this path if needed
my_path = '/content/drive/My Drive/Colab Notebooks/'

# change to this path
os.chdir(my_path)

# verify present working directory. It should be identical to 'my_path'
!pwd

Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks

In [ ]:
## assuming you have a 'data' folder in your 'My Drive/Colab Notebooks' folder, where a dataset (e.g., 'california_cities.csv') exists
## if you don't have the 'data' folder, create one

df = pd.read_csv('data/california_cities.csv')

display(df.head())
display(df.tail())

,Unnamed: 0,city,latd,longd,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2,area_water_percent
0,0,Adelanto,34.576111,-117.432778,875.0,2871.0,31765,56.027,56.009,0.018,145.107,145.062,0.046,0.03
1,1,AgouraHills,34.153333,-118.761667,281.0,922.0,20330,7.822,7.793,0.029,20.260,20.184,0.076,0.37
2,2,Alameda,37.756111,-122.274444,NaN,33.0,75467,22.960,10.611,12.349,59.465,27.482,31.983,53.79
3,3,Albany,37.886944,-122.297778,NaN,43.0,18969,5.465,1.788,3.677,14.155,4.632,9.524,67.28
4,4,Alhambra,34.081944,-118.135000,150.0,492.0,83089,7.632,7.631,0.001,19.766,19.763,0.003,0.01

,Unnamed: 0,city,latd,longd,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2,area_water_percent
477,477,Yountville,38.403056,-122.362222,30.0,98.0,2933,1.531,1.531,0.000,3.966,3.966,0.000,0.00
478,478,Yreka,41.726667,-122.637500,787.0,2582.0,7765,10.053,9.980,0.073,26.036,25.847,0.188,0.72
479,479,YubaCity,39.134722,-121.626111,18.0,59.0,64925,14.656,14.578,0.078,37.959,37.758,0.201,0.53
480,480,Yucaipa,34.030278,-117.048611,798.0,2618.0,51367,27.893,27.888,0.005,72.244,72.231,0.013,0.02
481,481,YuccaValley,34.133333,-116.416667,1027.0,3369.0,20700,40.015,40.015,0.000,103.639,103.639,0.000,0.00

### Option 2. Loading data from an URL

In [ ]:
# load data 
# url = 'https://raw.githubusercontent.com/smbillah/ist526/main/california_cities.csv'
url = 'https://raw.githubusercontent.com/smbillah/ist526/main/iris.csv'

# use pandas to read csv file 
df2 = pd.read_csv(url)
display(df2.head())
display(df2.tail())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

### Preprocessing 1: data cleaning

In [ ]:
# removing non-numeric, unwanted columns, and rows with missing data
df = df.drop(['Unnamed: 0', 'city', 'latd', 'longd'], axis = 1)

# removing rows with empty values
df.dropna(inplace=True)
display(df.head())

,elevation_m,elevation_ft,population_total,area_total_sq_mi,area_land_sq_mi,area_water_sq_mi,area_total_km2,area_land_km2,area_water_km2,area_water_percent
0,875.0,2871.0,31765,56.027,56.009,0.018,145.107,145.062,0.046,0.03
1,281.0,922.0,20330,7.822,7.793,0.029,20.260,20.184,0.076,0.37
4,150.0,492.0,83089,7.632,7.631,0.001,19.766,19.763,0.003,0.01
5,127.0,417.0,47823,7.472,7.472,0.000,19.352,19.352,0.000,0.00
6,1332.0,4370.0,2827,2.449,2.435,0.014,6.342,6.306,0.036,0.57

# Interpret Scagnostic
[library](https://github.com/haishiro/pyscagnostics)

## Install library

In [ ]:
# installation - run it once
!pip install pyscagnostics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement pyscagnostics (from versions: none)
ERROR: No matching distribution found for pyscagnostics

## loading + clearning data

In [ ]:
from pyscagnostics import scagnostics

## make sure all columns are numeric
display(df.head())

## Get scores for the data frame

In [ ]:
# get sgagnostic scores from the library
results = scagnostics(df)

## Convert scores to Scagnostic-format

In [ ]:
# post-process results to make scagnostic

# create 9-attribute list
score_names = ['Outlying', 'Skewed', 'Clumpy', 'Sparse', 'Striated', 'Convex', 'Skinny', 'Stringy', 'Monotonic']

# add a new data source
data = {'score_names':score_names}

scores = None

# iterate over the reasults
for i, j, result in results:
  (measures, bins) = result  
  scores = measures
  
  ## debug
  print(i, j, measures)
  
  col_name = "{}_{}".format(i, j)  
  
  # copy scores
  row = []
  row.append(scores['Outlying'])
  row.append(scores['Skewed'])
  row.append(scores['Clumpy'])
  row.append(scores['Sparse'])
  row.append(scores['Striated'])
  row.append(scores['Convex'])
  row.append(scores['Skinny'])
  row.append(scores['Stringy'])
  row.append(scores['Monotonic'])

  # add current 'col_name' as key and 'row' as value to 'data'
  data[col_name] = row;
# end for

elevation_ft population_total {'Outlying': 0.9182228125792041, 'Skewed': 0.6652059378840942, 'Clumpy': 0.16267942583732056, 'Sparse': 0.024597391802917166, 'Striated': 0.14285714285714285, 'Convex': 0.42477481340329676, 'Skinny': 0.5929058907681155, 'Stringy': 0.4614012021036814, 'Monotonic': 0.011712367937244266}
elevation_ft area_total_sq_mi {'Outlying': 0.6779274420779277, 'Skewed': 0.8290144725679989, 'Clumpy': 0.20574162679425836, 'Sparse': 0.03847275884004502, 'Striated': 0.09195402298850575, 'Convex': 0.3778435120265764, 'Skinny': 0.5264780976962471, 'Stringy': 0.4280187148601713, 'Monotonic': 0.02513322478329541}
elevation_ft area_land_sq_mi {'Outlying': 0.7014973002555125, 'Skewed': 0.8078404077857002, 'Clumpy': 0.302158273381295, 'Sparse': 0.03900452938601761, 'Striated': 0.10112359550561797, 'Convex': 0.37831906384944025, 'Skinny': 0.5176015892030219, 'Stringy': 0.43404373177842565, 'Monotonic': 0.04222477530790023}
elevation_ft area_water_sq_mi {'Outlying': 0.7999396130003398, 'Skewed': 0.8005553469194122, 'Clumpy': 0.02508783367277597, 'Sparse': 0.033295479399871306, 'Striated': 0.36666666666666664, 'Convex': 0.04673229038827894, 'Skinny': 0.7516358784352565, 'Stringy': 0.7471485545902556, 'Monotonic': 0.016950495199945487}
elevation_ft area_water_percent {'Outlying': 0.6259859344883465, 'Skewed': 0.7850054801932214, 'Clumpy': 0.048141624705539836, 'Sparse': 0.03406568076626828, 'Striated': 0.2087912087912088, 'Convex': 0.05267422462825311, 'Skinny': 0.679693312055371, 'Stringy': 0.5380290370370371, 'Monotonic': 0.024013899273530707}
population_total area_total_sq_mi {'Outlying': 1.2975435609909258, 'Skewed': 0.5489967503710934, 'Clumpy': 0.09691024940334127, 'Sparse': 0.021126638362223945, 'Striated': 0.0, 'Convex': 0.632308362351904, 'Skinny': 0.45670599299147685, 'Stringy': 0.3553964120370371, 'Monotonic': 0.5434464580363803}
population_total area_land_sq_mi {'Outlying': 1.2536036754931068, 'Skewed': 0.6854846958135905, 'Clumpy': 0.09748682338521299, 'Sparse': 0.025330890826199493, 'Striated': 0.0, 'Convex': 0.7552785595111826, 'Skinny': 0.28022367923962743, 'Stringy': 0.31696093163035305, 'Monotonic': 0.5168424874993294}
population_total area_water_sq_mi {'Outlying': 0.8838728496210597, 'Skewed': 0.826069070300225, 'Clumpy': 0.4988235294117647, 'Sparse': 0.040642593694088944, 'Striated': 0.08108108108108109, 'Convex': 0.41553459145331917, 'Skinny': 0.5773460677569814, 'Stringy': 0.5899768386425431, 'Monotonic': 0.01393174174164842}
population_total area_water_percent {'Outlying': 0.9627724412920503, 'Skewed': 0.7689818609330639, 'Clumpy': 0.3990498812351544, 'Sparse': 0.03815413837408967, 'Striated': 0.1702127659574468, 'Convex': 0.23980121406787763, 'Skinny': 0.5369318495138469, 'Stringy': 0.5524031086161263, 'Monotonic': 0.0026955085561389774}
area_total_sq_mi area_land_sq_mi {'Outlying': 1.2376564837412611, 'Skewed': 0.5633960742789834, 'Clumpy': 0.5518867924528302, 'Sparse': 0.02286113303809152, 'Striated': 0.25925925925925924, 'Convex': 0.5288034418789042, 'Skinny': 0.5859651327669323, 'Stringy': 0.5477084898572503, 'Monotonic': 0.9682467402143292}
area_total_sq_mi area_water_sq_mi {'Outlying': 0.7288795077129513, 'Skewed': 0.704149393414128, 'Clumpy': 0.5639810426540285, 'Sparse': 0.03274090105547851, 'Striated': 0.05555555555555555, 'Convex': 0.27668765035173, 'Skinny': 0.4793877901895216, 'Stringy': 0.45199793728854065, 'Monotonic': 0.04525235542363963}
area_total_sq_mi area_water_percent {'Outlying': 0.7701035336224077, 'Skewed': 0.7831137670690373, 'Clumpy': 0.40669856459330145, 'Sparse': 0.036477553706106634, 'Striated': 0.027777777777777776, 'Convex': 0.22156898366438846, 'Skinny': 0.6480584864770147, 'Stringy': 0.5055190647534558, 'Monotonic': 0.0017708920811375464}
area_land_sq_mi area_water_sq_mi {'Outlying': 0.7341671727222608, 'Skewed': 0.7924173106253154, 'Clumpy': 0.5402843601895735, 'Sparse': 0.033203692927797714, 'Striated': 0.1111111111111111, 'Convex': 0.269941805525166, 'Skinny': 0.6152306298029198, 'Stringy': 0.45199793728854065, 'Monotonic': 0.0008125260151141453}
area_land_sq_mi area_water_percent {'Outlying': 0.7349406031151586, 'Skewed': 0.7883289935265113, 'Clumpy': 0.3818615751789976, 'Sparse': 0.03406568076626828, 'Striated': 0.0958904109589041, 'Convex': 0.1722076132815518, 'Skinny': 0.6748665099281679, 'Stringy': 0.5120000000000001, 'Monotonic': 0.008454491106642939}
area_water_sq_mi area_water_percent {'Outlying': 0.2735258152168063, 'Skewed': 0.8391435801001006, 'Clumpy': 0.2447058823529412, 'Sparse': 0.11269233172317793, 'Striated': 0.05172413793103448, 'Convex': 0.3210307150150883, 'Skinny': 0.6094044318214007, 'Stringy': 0.34972530052592044, 'Monotonic': 0.6578629678762136}

## Create a dataframe for scagnostic visualization

In [ ]:
# convert 'data' to data-frame named 'df_scagnostic'
df_scagnostic = pd.DataFrame.from_dict(data);

# make the first column 'score_names' to index
df_scagnostic.set_index('score_names', inplace=True)

# check out the dataframe
display(df_scagnostic.head(9))

,elevation_ft_population_total,elevation_ft_area_total_sq_mi,elevation_ft_area_land_sq_mi,elevation_ft_area_water_sq_mi,elevation_ft_area_water_percent,population_total_area_total_sq_mi,population_total_area_land_sq_mi,population_total_area_water_sq_mi,population_total_area_water_percent,area_total_sq_mi_area_land_sq_mi,area_total_sq_mi_area_water_sq_mi,area_total_sq_mi_area_water_percent,area_land_sq_mi_area_water_sq_mi,area_land_sq_mi_area_water_percent,area_water_sq_mi_area_water_percent
score_names,,,,,,,,,,,,,,,
Outlying,0.918223,0.677927,0.701497,0.799940,0.625986,1.297544,1.253604,0.883873,0.962772,1.237656,0.728880,0.770104,0.734167,0.734941,0.273526
Skewed,0.665206,0.829014,0.807840,0.800555,0.785005,0.548997,0.685485,0.826069,0.768982,0.563396,0.704149,0.783114,0.792417,0.788329,0.839144
Clumpy,0.162679,0.205742,0.302158,0.025088,0.048142,0.096910,0.097487,0.498824,0.399050,0.551887,0.563981,0.406699,0.540284,0.381862,0.244706
Sparse,0.024597,0.038473,0.039005,0.033295,0.034066,0.021127,0.025331,0.040643,0.038154,0.022861,0.032741,0.036478,0.033204,0.034066,0.112692
Striated,0.142857,0.091954,0.101124,0.366667,0.208791,0.000000,0.000000,0.081081,0.170213,0.259259,0.055556,0.027778,0.111111,0.095890,0.051724
Convex,0.424775,0.377844,0.378319,0.046732,0.052674,0.632308,0.755279,0.415535,0.239801,0.528803,0.276688,0.221569,0.269942,0.172208,0.321031
Skinny,0.592906,0.526478,0.517602,0.751636,0.679693,0.456706,0.280224,0.577346,0.536932,0.585965,0.479388,0.648058,0.615231,0.674867,0.609404
Stringy,0.461401,0.428019,0.434044,0.747149,0.538029,0.355396,0.316961,0.589977,0.552403,0.547708,0.451998,0.505519,0.451998,0.512000,0.349725
Monotonic,0.011712,0.025133,0.042225,0.016950,0.024014,0.543446,0.516842,0.013932,0.002696,0.968247,0.045252,0.001771,0.000813,0.008454,0.657863

## Finally, visualize scagnostic

In [ ]:
# now that our dataframe is in perfect condition, visualiza it with plotly
import plotly.express as px

fig = px.imshow(df_scagnostic, text_auto=True, aspect="auto")
fig.update_xaxes(side="top")
fig.show()

# Scatterplot Matrix

In [ ]:
import plotly.express as px

# select features/columns 
# features = ['petal.length', 'sepal.length', 'petal.width', 'sepal.width']

fig = px.scatter_matrix(
    df2,
    # dimensions=features,
    color="variety"
)

## adjust height and width of subplot
fig.update_layout(
  autosize=False,
  width=1200,
  height=1200,
)

fig.update_traces(diagonal_visible=False)
fig.show()

Interpretation: ??